version: "3.8"
services:
    db:
        image: postgres:latest
        container_name: pgDB
        ports:
        - "5432:5432"
        networks:
        - custom
        environment:
            POSTGRES_DB: "libreria"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "123"
        volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
        - db-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: on-failure:5
        container_name: pgAdmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "123"
            PGADMIN_LISTEN_PORT: "80"
        ports:
        - "8080:80"
        networks:
        - custom
        depends_on:
        - db

    scraper:
        build: ./Container_C
        container_name: pyscraper
        restart: on-failure:5
        networks:
            - custom  
        volumes:
            - type: bind
              source: ./Container_C
              target: /usr/src/Container_C
        depends_on: 
            - db
        restart: on-failure:10
        env_file:
            - ./Container_C/env.list

    flask:
        build: ./Container_D
        restart: on-failure:5
        container_name: pyflask
        expose:
            - "5000"
        ports:
            - "5000:5000"
        networks:
            - custom
        volumes:
            - type: bind
              source: ./Container_D
              target: /usr/src/Container_D
        depends_on:
            - db
        environment:
            - FLASK_APP=app.py
        env_file:
            - ./Container_D/env.list
            
volumes:
    db-data:
    pgadmin-data:

networks:
  custom:
        driver: bridge